[project]
name = "ai"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.1",
    "google-genai>=1.49.0",
    "python-dotenv>=1.2.1",
    "sentence-transformers>=5.1.2",
    "tqdm>=4.67.1",
    "uvicorn>=0.38.0",
]
